2025-08-06 14:22:15,095 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:31:00,908 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:31:05,072 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:42:03,178 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 14:44:14,423 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:48:04,600 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 15 CIAs disponíveis
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-06 14:48:59,955 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-06 14:48:59,963 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-06 14:48:59,964 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-06 14:48:59,965 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-06 14:48:59,966 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-06 14:48:59,967 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-06 14:48:59,970 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-06 14:48:59,971 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-06 14:56:41,459 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 15:00:40,989 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-06 15:00:50,909 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:00:53,518 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:01:00,475 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:03:11,785 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:04:59,069 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:05:41,895 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:50:49,503 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 15:51:35,267 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 15:53:38,728 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:07:14,365 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:09:59,095 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:33:03,197 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:33:17,198 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:34:07,517 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:35:19,524 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:35:25,914 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:36:52,382 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:37:04,825 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:37:42,878 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-06 16:38:11,423 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:38:57,247 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:40:48,016 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:41:08,561 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-06 16:41:26,417 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:49:45,206 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:49:46,940 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:51:13,154 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:51:19,606 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:53:27,911 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:53:29,827 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:57:14,295 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 17:01:32,483 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 17:01:35,472 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:02:08,950 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:02:08,997 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:02:27,240 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:02:27,260 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:15,085 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:04:15,119 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:18,465 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:18,498 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:20,304 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:32,533 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:04:32,570 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:30,147 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:30,171 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:33,128 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:09:33,157 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:35,895 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:35,905 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:12:13,793 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:13:01,098 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:13:59,767 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:14:09,758 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:16:29,807 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:19:32,972 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:19:36,434 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:35:18,703 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:38:41,802 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 09:38:57,057 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 09:39:02,975 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 09:45:18,447 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 09:45:21,323 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 09:48:34,446 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 09:50:09,259 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:50:38,706 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:50:44,336 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:52:41,260 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 09:52:44,890 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 09:52:46,977 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 09:52:57,516 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 09:53:07,997 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 09:53:41,738 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:18:08,112 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:18:09,709 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:18:45,548 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:19:04,774 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:19:10,196 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:19:27,797 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 15 CIAs disponíveis
2025-08-07 10:19:27,797 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-07 10:19:27,797 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Hdi']
2025-08-07 10:19:27,797 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-07 10:19:27,799 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:19:27,804 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Hdi']
2025-08-07 10:19:27,804 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Hdi - 01-2025
2025-08-07 10:20:11,440 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Hdi com sucesso
2025-08-07 10:20:11,440 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-07 10:20:11,443 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-07 10:20:11,446 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:20:11,449 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Hdi na competência 01-2025
2025-08-07 10:20:11,450 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-07 10:20:11,686 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 43.89 segundos
2025-08-07 10:25:37,013 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:25:38,783 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:25:39,307 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:25:47,525 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 15 CIAs disponíveis
2025-08-07 10:25:47,525 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-07 10:25:47,525 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Hdi']
2025-08-07 10:25:47,526 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-07 10:25:47,527 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:25:47,531 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Hdi']
2025-08-07 10:25:47,531 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Hdi - 01-2025
2025-08-07 10:26:30,714 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Hdi com sucesso
2025-08-07 10:26:30,714 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-07 10:26:30,717 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-07 10:26:30,721 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:26:30,724 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Hdi na competência 01-2025
2025-08-07 10:26:30,726 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-07 10:26:30,820 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 43.30 segundos
2025-08-07 10:30:58,969 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:31:00,002 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:31:00,885 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:31:19,864 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:31:26,510 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:31:27,915 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:32:11,955 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:32:16,604 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:33:24,433 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:33:29,801 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:33:32,823 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:33:33,271 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 10:33:50,525 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:34:12,787 - django.request - ERROR - Internal Server Error: /api/buscar-cias/
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 180, in buscar_cias_api
    dba.inserir_caixa_declarado(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        id_cia=id_cia,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        valor_liquido=valor_liquido
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: DBA.inserir_caixa_declarado() got an unexpected keyword argument 'valor_bruto'
2025-08-07 10:34:24,360 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:35:19,874 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:35:56,018 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:35:59,530 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:00,998 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:01,482 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:02,121 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:03,184 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:03,865 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:04,365 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:04,721 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:36:21,097 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 15 CIAs disponíveis
2025-08-07 10:36:21,097 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 2 CIAs e competência 01-2025
2025-08-07 10:36:21,098 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco', 'Hdi']
2025-08-07 10:36:21,098 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-07 10:36:21,099 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:36:21,108 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:36:21,110 - extrato_app.CoreData.batch_runner - INFO -  CIAs que ainda serão processadas: ['Bradesco', 'Hdi']
2025-08-07 10:36:21,111 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Bradesco - 01-2025
2025-08-07 10:36:37,217 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Bradesco com sucesso
2025-08-07 10:36:37,217 - extrato_app.CoreData.batch_runner - INFO - Processando CIA: Hdi - 01-2025
2025-08-07 10:37:19,445 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído para Hdi com sucesso
2025-08-07 10:37:19,445 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-07 10:37:19,448 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-07 10:37:19,451 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:37:19,454 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-07 10:37:19,454 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_hdi WHERE competencia = '01-2025' LIMIT 1;
2025-08-07 10:37:19,456 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Hdi na competência 01-2025
2025-08-07 10:37:19,457 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 2 CIAs (solicitadas + geradas anteriormente)
2025-08-07 10:37:19,681 - extrato_app.CoreData.batch_runner - INFO - Processamento concluído em 58.58 segundos
2025-08-07 10:40:12,227 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:40:13,267 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:43:26,718 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:43:37,953 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:44:01,611 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:45:13,571 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:45:35,736 - django.request - ERROR - Internal Server Error: /api/buscar-cias/
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 180, in buscar_cias_api
    dba.inserir_caixa_declarado(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        id_cia=id_cia,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        valor_liquido=valor_liquido
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: DBA.inserir_caixa_declarado() got an unexpected keyword argument 'valor_bruto'
2025-08-07 10:49:05,972 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:49:14,362 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:49:17,143 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:55:38,345 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:56:10,057 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 10:57:03,527 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:57:49,847 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:57:58,617 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 10:58:55,901 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:58:57,492 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 10:59:56,618 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:00:31,039 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:02:25,125 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:03:09,264 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:03:21,777 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:03:32,624 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:03:37,806 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:03:38,192 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 11:13:30,549 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:13:39,136 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:18:40,051 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:19:14,464 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:19:18,277 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:47:04,604 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:47:24,937 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 11:47:47,780 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 11:52:30,726 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:54:34,494 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:57:19,526 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:57:20,889 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 11:57:21,066 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 11:58:13,423 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:00:22,521 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:07:05,770 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:07:06,022 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 14:20:12,243 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:20:13,138 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:20:15,878 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:20:17,355 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:20:23,810 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:20:30,028 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:23:36,531 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:23:37,594 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:23:38,302 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:23:39,403 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:23:40,419 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:23:41,387 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:27:31,568 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:31:06,686 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:34:36,977 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:40:34,751 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:40:49,968 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:43:03,008 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 14:43:13,142 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:43:18,335 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:45:02,007 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:47:05,646 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 14:47:11,554 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 14:48:29,601 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:51:14,283 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 14:57:18,749 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 14:57:21,447 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 15:29:08,834 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:19,169 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:22,952 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:24,665 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:25,523 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:26,339 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:27,433 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:28,611 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:29,210 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:30,929 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:31,664 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:32,986 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:39,915 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:41,490 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:41,962 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:43,144 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:44,043 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:45,144 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:47,281 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:48,005 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:49,244 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:50,038 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:31:53,132 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:32:33,566 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:39:37,702 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 15:40:08,310 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:40:08,593 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 15:40:09,804 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:40:10,704 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:40:29,768 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:33,690 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:34,910 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:54,602 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:55,962 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:56,439 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:56,863 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:44:57,351 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:46:03,897 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:48:04,389 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:48:05,936 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:48:08,006 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:48:08,483 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:48:09,657 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:48:10,680 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:15,020 - django.request - ERROR - Internal Server Error: /atualizar-relatorios/
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "request.path.startswith('/atualizar-relatorios')"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 115, in atualizar_relatorios
    return render(request, 'atualizar_relatorios.html', {
        'cias_opt': cias_list
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('/atualizar-relatorios')' from 'request.path.startswith('/atualizar-relatorios')'
2025-08-07 15:49:15,067 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:24,283 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:25,922 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:26,570 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:27,440 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:28,079 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:28,853 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:29,637 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:31,169 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:31,984 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:32,688 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:33,069 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:34,816 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:37,009 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:37,389 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:38,099 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:38,615 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:40,020 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:49:42,555 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:50:32,068 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:56:51,642 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:56:52,564 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:56:53,394 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:58:51,510 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:58:53,711 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:58:55,158 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:58:56,870 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:58:58,616 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:58:59,249 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:00,091 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:00,608 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:02,190 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:13,080 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:14,960 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:19,883 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:20,227 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:20,437 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:21,444 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:26,957 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:27,000 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:27,351 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:27,393 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:27,809 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:28,499 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:32,866 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:42,146 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 15:59:51,569 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:00:03,403 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:00:06,026 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:00:06,833 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:00:07,864 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:00:08,635 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:00:09,502 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:01:20,871 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:01:21,643 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:02:36,543 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:02:50,354 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:02:51,098 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:02:52,069 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:02:53,032 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:02:53,683 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:08,352 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:15,859 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:33,479 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:39,131 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:49,534 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:53,715 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:54,658 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:56,472 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:03:59,100 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:07:11,612 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:07:40,101 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:07:41,196 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:07:41,809 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:15:01,629 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:15:27,338 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:15:44,687 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:16:01,646 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:16:09,527 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:16:18,124 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-07 16:17:52,489 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:17:57,751 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-07 16:18:05,264 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:18:10,554 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:18:11,810 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:18:12,268 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:18:12,942 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:21:39,578 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:21:56,928 - django.security.csrf - WARNING - Forbidden (CSRF token from the 'X-Csrftoken' HTTP header has incorrect length.): /api/verificar-relatorios
2025-08-07 16:24:02,617 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:24:15,279 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:24:30,853 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:25:13,745 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:25:17,318 - django.security.csrf - WARNING - Forbidden (CSRF token from the 'X-Csrftoken' HTTP header has incorrect length.): /api/verificar-relatorios
2025-08-07 16:25:32,522 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:26:20,321 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:28:28,270 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:33:13,827 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:33:14,047 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 16:34:05,491 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:34:08,872 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:34:12,418 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:34:15,960 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:34:18,068 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:34:18,389 - django.request - WARNING - Not Found: /favicon.ico
2025-08-07 16:34:33,737 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:34:58,947 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:35:23,745 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:35:26,596 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-07 16:35:30,538 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:37:51,977 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:37:53,061 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:37:56,266 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:38:57,359 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 16:47:26,178 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\ds4.py changed, reloading.
2025-08-07 16:47:27,581 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 16:55:25,005 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\ds4.py changed, reloading.
2025-08-07 17:00:49,743 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:08:48,773 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:10:33,427 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
2025-08-07 17:10:44,815 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:11:40,240 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:11:40,688 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:11:41,196 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:11:43,300 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:11:47,560 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-07 17:13:37,600 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\CoreData\dba.py changed, reloading.
